# Юнит 2. Разведывательный анализ данных
# PYTHON-9. Возможности библиотеки Numpy для работы с данными 

In [58]:
import numpy as np

# Yahoo.Finance
import pandas_datareader as pdr
import datetime

# Google.Finance
import quandl

import matplotlib.pyplot as plt
# %matplotlib inline

In [12]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[5, 6, 1],
       [2, 2, 8],
       [7, 8, 1]])

In [11]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
# my_secret
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [36]:
np.random.randint(0, 6, (3, 3))

array([[4, 0, 4],
       [4, 5, 5],
       [0, 1, 3]])

In [40]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

# Задание

In [59]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [90]:
big_secret[:,:5]

array([[14.        , 10.        ,  6.        , 56.        , 40.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [ 0.        ,  1.        ,  4.        ,  9.        , 16.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [14.        , 10.        ,  6.        , 56.        , 40.        ]])

In [65]:
# 1.Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:
big_secret[:, -1].sum().round(2)

3154.33

In [86]:
# 2.Выделите из каждой строки массива big_secret первые 5 элементов. 
# Чему равна сумма элементов главной диагонали получившейся матрицы? 
# Округлите ответ до двух цифр после запятой:

# Сокращенная матрица и начальные параметры для расчёта
small_secret = big_secret[:,:5]
sum_diagonal = 0
j = 0

# Считаем главную диагональ
for i in small_secret:
    sum_diagonal += i[j]
    j += 1
    
print('sum=',round(sum_diagonal, 2))

sum= 121.37


In [96]:
# 3.Выделите из каждой строки массива big_secret последние 5 элементов. 
# Чему равно произведение элементов главной диагонали получившейся матрицы? 
# Введите полученный результат без изменений и округлений.

# Выделяем последние 5 элементов из строк и определяем параметры
finish_5 = big_secret[:, -5:]
mult_diagonal = 1
j = 0

# Считаем главную диагональ
for i in finish_5:
    print(i[j])
    mult_diagonal *= i[j]
    j += 1

print('multiplier=',mult_diagonal)

460.0
33.075670817082454
2304.0
33.13608305156178
294.0
multiplier= 341505315559.2347
